In [1]:
import pandas as pd

# Load data from CSV file
data = pd.read_csv('tab_data.csv')

# Check for duplicated rows
duplicated_rows = data[data.duplicated(keep=False)]

if not duplicated_rows.empty:
    # Save duplicated rows to a new CSV file
    duplicated_rows.to_csv('duplicate_data.csv', index=False)
    
    # Display number of duplicate rows and their row numbers
    print(f"Number of duplicate rows found: {len(duplicated_rows)}")
    print("Duplicate rows found in rows:", ", ".join(map(str, duplicated_rows.index)))
else:
    print("No duplicate rows found.")

No duplicate rows found.

In [2]:
import pandas as pd

# Load data from CSV file
data = pd.read_csv('Modified_Cleaned_1.csv')

# Check for duplicated rows
duplicated_rows = data[data.duplicated(keep=False)]

if not duplicated_rows.empty:
    # Save duplicated rows to a new CSV file
    duplicated_rows.to_csv('duplicate_data_1.csv', index=False)
    
    # Display number of duplicate rows and their row numbers
    print(f"Number of duplicate rows found: {len(duplicated_rows)}")
    print("Duplicate rows found in rows:", ", ".join(map(str, duplicated_rows.index)))
else:
    print("No duplicate rows found.")

Number of duplicate rows found: 5314

In [3]:
import pandas as pd

# Load data from CSV file
data = pd.read_csv('Modified_Cleaned_1.csv')

# Find duplicated rows
duplicated_rows = data[data.duplicated(keep=False)]

if not duplicated_rows.empty:
    # Group by the entire row to find unique rows
    grouped = duplicated_rows.groupby(list(duplicated_rows.columns))
    
    # Iterate over unique rows
    for _, group in grouped:
        # Find the row numbers of the duplicates
        duplicate_indices = group.index.tolist()
        
        # Create a DataFrame containing original row and its duplicates
        duplicated_data = data.loc[duplicate_indices]
        
        # Write the duplicated data to a new CSV file
        duplicated_data.to_csv(f'duplicate_row_{duplicate_indices[0]}.csv', index=False)
        
        # Display information about duplicated rows
        print(f"Original Row Number: {duplicate_indices[0]}")
        print(f"Number of Duplicates: {len(duplicate_indices)}")
        print(f"Duplicated Row Numbers: {', '.join(map(str, duplicate_indices))}")
        print("-" * 50)
else:
    print("No duplicate rows found.")

Original Row Number: 6
Number of Duplicates: 142
Duplicated Row Numbers: 6, 16, 55, 79, 145, 187, 271, 429, 442, 500, 517, 578, 625, 686, 704, 730, 856, 901, 1032, 1056, 1142, 1330, 1422, 1454, 1534, 1540, 1708, 1810, 1819, 1836, 1839, 1883, 1892, 1901, 1954, 1974, 2053, 2167, 2275, 2390, 2449, 2489, 2536, 2621, 2673, 2687, 2699, 2710, 2754, 2763, 2779, 2866, 2876, 3077, 3154, 3168, 3210, 3227, 3268, 3271, 3292, 3301, 3342, 3413, 3452, 3512, 3534, 3536, 3596, 3617, 3629, 3658, 3703, 3740, 3826, 3838, 3891, 3922, 3968, 3999, 4008, 4032, 4084, 4087, 4094, 4101, 4120, 4170, 4195, 4204, 4239, 4276, 4277, 4362, 4385, 4484, 4501, 4551, 4570, 4573, 4814, 4844, 4851, 4863, 4867, 4882, 4888, 5035, 5079, 5089, 5104, 5300, 5389, 5417, 5419, 5470, 5532, 5659, 5781, 5860, 5883, 5891, 5912, 5921, 5944, 6026, 6254, 6287, 6301, 6334, 6346, 6460, 6529, 6556, 6591, 6734, 6783, 6796, 6801, 6993, 7081, 7106
--------------------------------------------------
Original Row Number: 61
Number of Duplicates: 136
Duplicated Row Numbers: 61, 211, 264, 270, 385, 449, 464, 485, 491, 524, 549, 586, 630, 671, 688, 735, 777, 841, 925, 929, 971, 1080, 1248, 1334, 1400, 1406, 1441, 1474, 1482, 1502, 1625, 1626, 1639, 1642, 1668, 1714, 1863, 1887, 1909, 1973, 1985, 2027, 2277, 2297, 2370, 2517, 2571, 2610, 2618, 2709, 2717, 2808, 2829, 2867, 2947, 2983, 3086, 3156, 3173, 3175, 3233, 3374, 3378, 3403, 3417, 3459, 3471, 3515, 3545, 3557, 3561, 3611, 3621, 3765, 3783, 3802, 3899, 3927, 3982, 4020, 4142, 4313, 4377, 4406, 4457, 4479, 4486, 4619, 4629, 4714, 4738, 4865, 4918, 5041, 5090, 5092, 5309, 5328, 5381, 5404, 5491, 5561, 5563, 5600, 5627, 5649, 5771, 5819, 5877, 5886, 5918, 5982, 6107, 6111, 6190, 6229, 6243, 6296, 6312, 6353, 6358, 6424, 6438, 6465, 6492, 6638, 6663, 6733, 6766, 6856, 6870, 6892, 6896, 6922, 7007, 7114
--------------------------------------------------
Original Row Number: 3
Number of Duplicates: 129
Duplicated Row Numbers: 3, 33, 52, 215, 231, 244, 283, 329, 334, 335, 346, 444, 596, 621, 648, 692, 721, 850, 883, 935, 1025, 1137, 1281, 1283, 1390, 1484, 1553, 1619, 1627, 1670, 1705, 1905, 1972, 1997, 2055, 2116, 2155, 2208, 2412, 2540, 2605, 2636, 2667, 2732, 2742, 2757, 2785, 2870, 2916, 2923, 2996, 3041, 3067, 3104, 3108, 3182, 3193, 3238, 3249, 3270, 3289, 3352, 3439, 3462, 3474, 3475, 3478, 3505, 3510, 3587, 3640, 3655, 3694, 3737, 3738, 3748, 3791, 3883, 3898, 3914, 3963, 3995, 4095, 4106, 4139, 4168, 4261, 4306, 4340, 4428, 4445, 4516, 4584, 4702, 4718, 4791, 4917, 4926, 4984, 5004, 5012, 5119, 5271, 5303, 5357, 5507, 5516, 5521, 5629, 5759, 5816, 5837, 5855, 5867, 5950, 5989, 6035, 6039, 6125, 6153, 6329, 6335, 6340, 6487, 6735, 7054, 7103, 7105, 7137
--------------------------------------------------
Original Row Number: 114
Number of Duplicates: 123
Duplicated Row Numbers: 114, 149, 181, 290, 368, 405, 440, 471, 653, 709, 712, 853, 934, 952, 1049, 1108, 1128, 1207, 1210, 1229, 1272, 1323, 1382, 1535, 1538, 1725, 1735, 1750, 1798, 1918, 2059, 2117, 2173, 2238, 2337, 2360, 2367, 2431, 2450, 2464, 2511, 2634, 2726, 2738, 2741, 2760, 2848, 2860, 2999, 3183, 3269, 3280, 3419, 3428, 3437, 3473, 3482, 3497, 3530, 3560, 3590, 3603, 3732, 3755, 3818, 3874, 3881, 4014, 4249, 4289, 4300, 4315, 4341, 4355, 4366, 4536, 4542, 4603, 4605, 4678, 4685, 4723, 4729, 4769, 4795, 4840, 4871, 4928, 4999, 5059, 5071, 5192, 5205, 5220, 5316, 5378, 5406, 5420, 5430, 5609, 5830, 5942, 5972, 6016, 6017, 6078, 6189, 6211, 6365, 6478, 6575, 6595, 6599, 6612, 6629, 6745, 6793, 6873, 6901, 7004, 7030, 7070, 7197
--------------------------------------------------
Original Row Number: 11
Number of Duplicates: 138
Duplicated Row Numbers: 11, 18, 76, 91, 131, 238, 281, 300, 319, 383, 423, 472, 473, 503, 652, 655, 748, 909, 1062, 1093, 1158, 1244, 1313, 1336, 1421, 1443, 1473, 1568, 1682, 1720, 1722, 1739, 1765, 1779, 1789, 1827, 1849, 1876, 1921, 2003, 2006, 2033, 2036, 2097, 2102, 2103, 2172, 2231, 2309, 2335, 2379, 2389, 2395, 2396, 2539, 2554, 2555, 2597, 2629, 2795, 2797, 2837, 2898, 2907, 2910, 2980, 3016, 3019, 3038, 3053, 3087, 3090, 3100, 3199, 3297, 3306, 3318, 3358, 3386, 3421, 3465, 3513, 3523, 3527, 3578, 3638, 3718, 3728, 3924, 3945, 3994, 4048, 4115, 4130, 4222, 4240, 4324, 4408, 4413, 4463, 4511, 4537, 4640, 4644, 4812, 4826, 4880, 4886, 4898, 4900, 4904, 4985, 4993, 5179, 5180, 5232, 5366, 5483, 5539, 5564, 5587, 5775, 5893, 5969, 6003, 6251, 6354, 6464, 6474, 6525, 6643, 6656, 6712, 6725, 6812, 6935, 6994, 7138
--------------------------------------------------
Original Row Number: 28
Number of Duplicates: 169
Duplicated Row Numbers: 28, 74, 84, 94, 143, 169, 170, 239, 307, 521, 525, 531, 534, 545, 611, 675, 687, 713, 821, 881, 916, 946, 1018, 1022, 1031, 1036, 1061, 1097, 1111, 1112, 1184, 1203, 1268, 1300, 1335, 1379, 1392, 1590, 1657, 1713, 1833, 1904, 1917, 1938, 1944, 1951, 1958, 2049, 2050, 2091, 2145, 2159, 2177, 2183, 2268, 2306, 2318, 2358, 2384, 2432, 2433, 2476, 2579, 2650, 2664, 2697, 2723, 2737, 2781, 2865, 2909, 3012, 3026, 3094, 3138, 3189, 3194, 3198, 3251, 3308, 3490, 3493, 3514, 3517, 3555, 3580, 3639, 3650, 3659, 3661, 3722, 3724, 3837, 3901, 3975, 4077, 4081, 4103, 4186, 4236, 4251, 4271, 4285, 4337, 4394, 4402, 4476, 4549, 4586, 4593, 4595, 4658, 4666, 4694, 4695, 4716, 4772, 4789, 4805, 4815, 4862, 5019, 5120, 5242, 5326, 5410, 5425, 5443, 5466, 5540, 5574, 5591, 5605, 5646, 5868, 5927, 5934, 5956, 5971, 5992, 6009, 6030, 6086, 6130, 6131, 6134, 6174, 6283, 6303, 6311, 6405, 6456, 6479, 6480, 6567, 6601, 6606, 6613, 6655, 6756, 6757, 6851, 6855, 6878, 6906, 6956, 7029, 7035, 7184
--------------------------------------------------
Original Row Number: 0
Number of Duplicates: 127
Duplicated Row Numbers: 0, 51, 98, 147, 175, 227, 253, 276, 369, 372, 376, 392, 426, 495, 532, 591, 604, 696, 782, 825, 833, 844, 860, 939, 943, 945, 978, 998, 1040, 1051, 1054, 1083, 1095, 1156, 1171, 1182, 1186, 1214, 1228, 1303, 1530, 1571, 1592, 1630, 1676, 1759, 1824, 1851, 1939, 2178, 2188, 2210, 2241, 2253, 2547, 2604, 2660, 2853, 2874, 3069, 3150, 3369, 3399, 3438, 3467, 3483, 3484, 3597, 3624, 3870, 3912, 3949, 4091, 4148, 4201, 4202, 4250, 4488, 4508, 4524, 4559, 4563, 4731, 4739, 4781, 4785, 4806, 4809, 4819, 4894, 4915, 4927, 4939, 5014, 5025, 5031, 5151, 5237, 5537, 5547, 5550, 5576, 5617, 5643, 5875, 5919, 5953, 6041, 6042, 6044, 6110, 6198, 6201, 6587, 6594, 6693, 6744, 6753, 6821, 6834, 6854, 6857, 6885, 6924, 6996, 7040, 7171
--------------------------------------------------
Original Row Number: 20
Number of Duplicates: 115
Duplicated Row Numbers: 20, 92, 95, 128, 222, 237, 299, 306, 344, 350, 420, 447, 522, 555, 559, 580, 779, 824, 831, 846, 876, 956, 995, 1007, 1114, 1177, 1227, 1262, 1284, 1294, 1328, 1353, 1355, 1363, 1386, 1403, 1452, 1589, 1669, 1685, 1693, 1767, 1786, 2000, 2104, 2127, 2364, 2459, 2552, 2568, 2609, 2644, 2649, 2680, 2811, 2857, 2946, 2951, 2973, 3001, 3116, 3136, 3214, 3223, 3258, 3385, 3422, 3426, 3477, 3506, 3539, 3575, 3633, 3660, 3763, 3861, 4055, 4143, 4165, 4387, 4436, 4493, 4555, 4613, 4689, 4749, 4838, 4852, 4933, 4987, 5175, 5236, 5355, 5362, 5403, 5523, 5623, 5822, 5905, 5906, 6180, 6192, 6219, 6318, 6420, 6445, 6619, 6647, 6705, 6706, 6898, 6973, 7000, 7094, 7149
--------------------------------------------------
Original Row Number: 21
Number of Duplicates: 121
Duplicated Row Numbers: 21, 48, 75, 161, 206, 233, 293, 365, 431, 469, 488, 603, 605, 659, 677, 857, 867, 914, 954, 1098, 1144, 1154, 1178, 1180, 1235, 1266, 1446, 1541, 1559, 1634, 1844, 1874, 1978, 2107, 2156, 2220, 2348, 2378, 2442, 2542, 2592, 2627, 2805, 2868, 2936, 3007, 3029, 3073, 3112, 3153, 3163, 3277, 3329, 3343, 3463, 3485, 3569, 3577, 3666, 3834, 3952, 4058, 4078, 4124, 4131, 4217, 4244, 4389, 4504, 4517, 4529, 4566, 4577, 4652, 4686, 4777, 4965, 4972, 4994, 5076, 5219, 5249, 5255, 5269, 5319, 5329, 5374, 5411, 5414, 5486, 5559, 5598, 5630, 5634, 5650, 5671, 5700, 5710, 5888, 5994, 6046, 6097, 6160, 6212, 6339, 6390, 6514, 6523, 6557, 6720, 6790, 6860, 6882, 6972, 6995, 7034, 7050, 7162, 7165, 7173, 7187
--------------------------------------------------
Original Row Number: 255
Number of Duplicates: 33
Duplicated Row Numbers: 255, 257, 888, 1147, 1965, 1990, 2007, 2176, 2291, 2312, 2478, 2804, 2952, 3107, 3165, 3323, 3830, 4116, 4284, 4429, 4467, 5181, 5244, 5515, 5538, 5656, 5721, 5913, 6332, 6374, 6640, 6795, 7178
--------------------------------------------------
Original Row Number: 216
Number of Duplicates: 41
Duplicated Row Numbers: 216, 218, 278, 325, 382, 433, 571, 594, 708, 723, 826, 1090, 1123, 1413, 1609, 1970, 1983, 3088, 3140, 3265, 3785, 4210, 4307, 4344, 4418, 4631, 4746, 4883, 5285, 5498, 5675, 5769, 5844, 5874, 6105, 6127, 6216, 6285, 6737, 6763, 7141
--------------------------------------------------
Original Row Number: 182
Number of Duplicates: 45
Duplicated Row Numbers: 182, 195, 205, 209, 992, 1198, 1493, 1591, 1610, 1638, 1808, 1813, 2250, 2346, 2569, 2587, 2939, 3049, 3065, 3074, 3360, 3601, 4163, 4193, 4305, 4435, 5376, 5553, 5685, 5691, 5827, 5841, 5996, 6150, 6151, 6233, 6238, 6244, 6247, 6391, 6544, 6702, 6913, 6991, 7074
--------------------------------------------------
Original Row Number: 81
Number of Duplicates: 51
Duplicated Row Numbers: 81, 109, 148, 166, 172, 302, 357, 667, 1191, 1279, 1607, 1866, 1913, 2328, 2401, 2690, 2749, 2815, 2941, 3311, 3361, 3398, 3593, 3609, 3677, 3695, 3709, 3758, 3985, 4121, 4393, 4449, 4722, 4891, 5322, 5323, 5460, 5500, 5753, 5785, 5858, 5889, 5897, 6177, 6184, 6411, 6685, 6871, 6930, 7055, 7185
--------------------------------------------------
Original Row Number: 135
Number of Duplicates: 50
Duplicated Row Numbers: 135, 436, 556, 760, 771, 1103, 1119, 1157, 1307, 1463, 1574, 1671, 1881, 2004, 2273, 2331, 2487, 2534, 2849, 2935, 2976, 3115, 3157, 3708, 3751, 3784, 3853, 3970, 4025, 4269, 4379, 4606, 4713, 4787, 4836, 5000, 5286, 5299, 5354, 5641, 5672, 5743, 5941, 6231, 6262, 6351, 6931, 7044, 7052, 7075
--------------------------------------------------
Original Row Number: 63
Number of Duplicates: 47
Duplicated Row Numbers: 63, 196, 292, 457, 1026, 1200, 1225, 1703, 1716, 1916, 1999, 2224, 2290, 2707, 2771, 2964, 3024, 3089, 3312, 3354, 3377, 3432, 3468, 3592, 3824, 4147, 4357, 4452, 4474, 4830, 4903, 4976, 5524, 5599, 5808, 5833, 5851, 6200, 6440, 6466, 6469, 6752, 6761, 6805, 6813, 6876, 7085
--------------------------------------------------
Original Row Number: 1
Number of Duplicates: 36
Duplicated Row Numbers: 1, 226, 427, 814, 878, 1070, 1438, 1694, 1778, 1793, 1906, 2040, 2061, 2421, 2556, 2651, 2659, 2753, 3098, 3273, 3295, 3379, 3855, 4128, 4166, 4411, 4531, 4539, 4599, 5733, 6413, 6430, 6616, 6776, 7022, 7108
--------------------------------------------------
Original Row Number: 30
Number of Duplicates: 43
Duplicated Row Numbers: 30, 85, 324, 637, 1165, 1437, 1677, 1756, 1835, 1915, 1920, 2142, 2272, 2611, 3203, 3553, 3856, 3931, 4051, 4219, 4231, 4356, 4414, 4446, 4459, 4590, 4730, 4733, 4876, 4909, 4919, 4959, 5040, 5274, 5495, 5585, 6118, 6264, 6268, 6444, 6858, 6941, 7110
--------------------------------------------------
Original Row Number: 224
Number of Duplicates: 44
Duplicated Row Numbers: 224, 510, 739, 811, 927, 1010, 1547, 1724, 1890, 2037, 2083, 2090, 2283, 2329, 2581, 3320, 3653, 4001, 4112, 4146, 4206, 4207, 4347, 4374, 4375, 4624, 4693, 4884, 5045, 5118, 5345, 5347, 5922, 5980, 6024, 6101, 6350, 6359, 6435, 6473, 6569, 6578, 6904, 7082
--------------------------------------------------
Original Row Number: 679
Number of Duplicates: 38
Duplicated Row Numbers: 679, 903, 968, 1130, 1451, 1701, 1702, 1782, 1956, 2338, 2425, 2467, 2488, 2612, 3125, 3212, 3226, 3516, 3613, 3920, 3987, 3989, 4140, 4728, 4859, 4930, 5122, 5143, 5265, 5635, 5640, 5862, 5869, 5931, 6051, 6155, 6607, 7016
--------------------------------------------------
Original Row Number: 210
Number of Duplicates: 42
Duplicated Row Numbers: 210, 707, 715, 788, 1015, 1085, 1133, 1395, 2302, 2303, 2342, 2890, 3033, 3325, 3390, 3762, 4082, 4214, 4359, 4427, 4541, 4585, 4932, 5082, 5168, 5373, 5518, 5542, 5595, 5645, 5687, 5736, 5789, 5920, 5954, 6158, 6171, 6250, 6256, 6259, 6481, 7036
--------------------------------------------------
Original Row Number: 108
Number of Duplicates: 36
Duplicated Row Numbers: 108, 115, 133, 249, 406, 408, 484, 1067, 1408, 1588, 1711, 1933, 2150, 2158, 3333, 3406, 3537, 3810, 3814, 4067, 4145, 4430, 4491, 4757, 5121, 5504, 5522, 5870, 6008, 6063, 6363, 6458, 6476, 6509, 6768, 6774
--------------------------------------------------
Original Row Number: 7
Number of Duplicates: 38
Duplicated Row Numbers: 7, 82, 190, 246, 461, 467, 716, 804, 843, 892, 990, 1361, 1520, 1689, 2236, 2296, 2748, 2917, 2929, 2957, 3244, 3706, 3984, 3992, 4033, 4085, 4453, 4572, 4978, 5116, 5375, 5568, 5836, 5907, 6043, 6073, 6123, 6620
--------------------------------------------------
Original Row Number: 17
Number of Duplicates: 37
Duplicated Row Numbers: 17, 912, 1008, 1253, 1351, 1425, 1558, 1585, 1614, 1699, 1870, 1889, 1948, 2171, 2615, 2847, 2942, 2971, 3918, 3947, 3964, 4403, 4638, 4655, 4724, 4860, 4940, 4948, 5038, 5110, 5288, 5405, 5613, 6315, 6810, 7048, 7157
--------------------------------------------------
Original Row Number: 50
Number of Duplicates: 28
Duplicated Row Numbers: 50, 72, 353, 494, 1209, 1226, 1444, 1467, 1898, 2026, 3000, 3032, 3531, 4321, 4482, 4589, 5036, 5256, 5258, 5264, 5821, 6050, 6067, 6079, 6342, 6917, 6964, 7072
--------------------------------------------------
Original Row Number: 193
Number of Duplicates: 36
Duplicated Row Numbers: 193, 266, 820, 918, 1220, 1240, 1267, 1296, 1615, 1854, 1884, 2071, 2528, 2577, 2595, 2968, 2995, 3119, 3152, 3225, 4018, 4144, 4630, 4977, 5140, 5152, 5341, 5487, 5583, 5601, 6027, 6147, 6323, 6400, 6921, 7071
--------------------------------------------------
Original Row Number: 673
Number of Duplicates: 36
Duplicated Row Numbers: 673, 812, 1201, 1345, 1393, 1712, 2028, 2544, 2873, 2948, 3160, 3376, 3576, 3858, 3937, 4335, 4824, 5067, 5159, 5184, 5196, 5272, 5533, 5719, 5801, 5882, 6210, 6343, 6372, 6401, 6457, 6667, 6724, 6977, 6990, 7123
--------------------------------------------------
Original Row Number: 35
Number of Duplicates: 37
Duplicated Row Numbers: 35, 165, 189, 516, 864, 904, 1100, 1418, 1419, 1762, 1768, 1896, 2506, 2567, 2633, 2762, 2998, 3372, 3375, 4199, 4499, 4890, 5001, 5032, 5211, 5224, 5229, 5536, 5592, 5695, 6083, 6253, 6293, 6455, 6528, 6572, 7107
--------------------------------------------------
Original Row Number: 160
Number of Duplicates: 36
Duplicated Row Numbers: 160, 174, 550, 600, 722, 1597, 1608, 1803, 2593, 2635, 2693, 2839, 2937, 2945, 3221, 3359, 3500, 3696, 3764, 3906, 4072, 4076, 4495, 4503, 5621, 5762, 5928, 6175, 6325, 6498, 6502, 6666, 6902, 6951, 7002, 7026
--------------------------------------------------
Original Row Number: 78
Number of Duplicates: 51
Duplicated Row Numbers: 78, 767, 928, 960, 961, 1002, 1065, 1232, 1731, 1743, 1952, 2075, 2099, 2124, 2134, 2336, 2513, 2557, 3011, 3055, 3066, 3075, 3132, 3338, 3416, 3757, 3781, 4003, 4114, 4343, 4425, 4473, 4583, 4656, 4942, 5117, 5145, 5247, 5280, 5395, 5455, 5519, 5614, 5772, 5812, 6011, 6352, 6399, 6727, 6743, 7028
--------------------------------------------------
Original Row Number: 274
Number of Duplicates: 38
Duplicated Row Numbers: 274, 418, 607, 701, 774, 1250, 1258, 1271, 1378, 1594, 1655, 1855, 2439, 2491, 2706, 2895, 2979, 3056, 3148, 3262, 3316, 3698, 3803, 3843, 4155, 4420, 4500, 4981, 5259, 5764, 5879, 6203, 6443, 6506, 6605, 6680, 7120, 7128
--------------------------------------------------
Original Row Number: 19
Number of Duplicates: 40
Duplicated Row Numbers: 19, 124, 152, 515, 785, 1488, 1513, 1523, 1679, 1823, 2024, 2160, 2423, 2608, 2807, 3133, 3340, 3446, 3547, 3787, 3865, 3908, 4056, 4256, 4598, 4604, 5085, 5266, 5315, 5407, 5534, 5697, 5741, 5810, 6106, 6517, 6584, 6853, 6989, 7089
--------------------------------------------------
Original Row Number: 548
Number of Duplicates: 42
Duplicated Row Numbers: 548, 764, 963, 1044, 1048, 1208, 1280, 1317, 1447, 1550, 1616, 1706, 1967, 2021, 2042, 2388, 2456, 2500, 3689, 3717, 3746, 4002, 4097, 4478, 4540, 4834, 5077, 5182, 5436, 5496, 5520, 5541, 5631, 5642, 6076, 6140, 6208, 6728, 7046, 7124, 7167, 7175
--------------------------------------------------
Original Row Number: 144
Number of Duplicates: 48
Duplicated Row Numbers: 144, 298, 508, 587, 638, 750, 908, 969, 1124, 1308, 1664, 1957, 2135, 2310, 2435, 2652, 2727, 2783, 3078, 3121, 3229, 3235, 3339, 3355, 3487, 3631, 4209, 4257, 4817, 4896, 4951, 4992, 5136, 5156, 5254, 5284, 5305, 5551, 5597, 6349, 6593, 6621, 6700, 6785, 6974, 7027, 7073, 7168
--------------------------------------------------
Original Row Number: 309
Number of Duplicates: 35
Duplicated Row Numbers: 309, 617, 698, 1076, 1420, 1552, 1565, 1660, 1667, 1776, 1986, 2137, 2502, 2643, 2701, 3499, 3675, 3815, 3965, 4635, 4821, 5267, 5845, 5908, 5976, 5981, 6237, 6300, 6579, 6658, 6754, 6872, 6881, 6916, 7196
--------------------------------------------------
Original Row Number: 102
Number of Duplicates: 30
Duplicated Row Numbers: 102, 173, 430, 1038, 1194, 1342, 1439, 1658, 1775, 1867, 2240, 2365, 2606, 2960, 3895, 3974, 3977, 4039, 4137, 4268, 4726, 4953, 4990, 5289, 5895, 6316, 6321, 6418, 6713, 7032
--------------------------------------------------
Original Row Number: 162
Number of Duplicates: 37
Duplicated Row Numbers: 162, 304, 439, 1150, 1212, 1292, 1606, 1831, 2125, 2279, 2480, 2538, 2619, 2648, 3004, 3346, 3641, 4152, 4405, 4448, 4750, 4776, 4937, 5084, 5127, 5128, 5476, 5693, 5757, 5945, 6371, 6392, 6543, 6630, 6841, 7093, 7166
--------------------------------------------------
Original Row Number: 316
Number of Duplicates: 44
Duplicated Row Numbers: 316, 339, 351, 513, 1058, 1173, 1518, 1653, 1707, 1873, 2899, 2914, 2931, 3081, 3381, 3574, 3731, 3846, 3851, 3972, 4182, 4490, 4645, 4745, 4827, 4929, 4983, 5311, 5418, 5531, 5581, 5669, 5892, 5951, 6186, 6320, 6387, 6422, 6477, 6598, 6835, 7012, 7092, 7115
--------------------------------------------------
Original Row Number: 154
Number of Duplicates: 37
Duplicated Row Numbers: 154, 360, 1237, 1532, 1661, 1871, 2468, 2580, 2594, 2653, 2838, 2984, 3196, 3219, 3337, 3348, 3435, 3680, 3782, 3888, 4017, 4304, 4378, 4485, 4661, 4893, 4924, 5252, 5371, 5439, 5608, 5667, 5740, 6149, 6863, 6910, 6923
--------------------------------------------------
Original Row Number: 250
Number of Duplicates: 44
Duplicated Row Numbers: 250, 256, 313, 380, 409, 414, 499, 970, 1030, 1259, 1276, 1310, 1312, 1481, 1704, 2039, 2152, 2186, 2204, 2259, 2694, 2728, 3022, 3027, 3171, 3753, 3812, 3879, 3958, 4510, 5048, 5087, 5123, 5313, 5552, 5573, 5900, 5930, 6036, 6081, 6441, 6484, 6746, 7155
--------------------------------------------------
Original Row Number: 1455
Number of Duplicates: 2
Duplicated Row Numbers: 1455, 1511
--------------------------------------------------
Original Row Number: 4680
Number of Duplicates: 2
Duplicated Row Numbers: 4680, 7122
--------------------------------------------------
Original Row Number: 2261
Number of Duplicates: 2
Duplicated Row Numbers: 2261, 5847
--------------------------------------------------
Original Row Number: 58
Number of Duplicates: 2
Duplicated Row Numbers: 58, 3971
--------------------------------------------------
Original Row Number: 780
Number of Duplicates: 2
Duplicated Row Numbers: 780, 5839
--------------------------------------------------
Original Row Number: 167
Number of Duplicates: 2
Duplicated Row Numbers: 167, 1064
--------------------------------------------------
Original Row Number: 4046
Number of Duplicates: 2
Duplicated Row Numbers: 4046, 5039
--------------------------------------------------
Original Row Number: 1678
Number of Duplicates: 2
Duplicated Row Numbers: 1678, 4664
--------------------------------------------------
Original Row Number: 2448
Number of Duplicates: 2

In [4]:
import pandas as pd

# Load data from CSV file
data = pd.read_csv('Modified_Cleaned_1.csv')

# Find duplicated rows
duplicated_rows = data[data.duplicated(keep=False)]

if not duplicated_rows.empty:
    # Iterate over each duplicated row
    for _, row in duplicated_rows.iterrows():
        # Find rows that are exactly identical (excluding the index column)
        identical_rows = data[(data == row).all(axis=1) & (data.index != row.name)]
        
        # If any identical rows are found, print information
        if not identical_rows.empty:
            print(f"Original Row Number: {row.name}")
            print(f"Number of Identical Duplicates: {len(identical_rows)}")
            print(f"Identical Duplicate Row Numbers: {', '.join(map(str, identical_rows.index))}")
            print("-" * 50)
else:
    print("No duplicate rows found.")

Original Row Number: 0
Number of Identical Duplicates: 126
Identical Duplicate Row Numbers: 51, 98, 147, 175, 227, 253, 276, 369, 372, 376, 392, 426, 495, 532, 591, 604, 696, 782, 825, 833, 844, 860, 939, 943, 945, 978, 998, 1040, 1051, 1054, 1083, 1095, 1156, 1171, 1182, 1186, 1214, 1228, 1303, 1530, 1571, 1592, 1630, 1676, 1759, 1824, 1851, 1939, 2178, 2188, 2210, 2241, 2253, 2547, 2604, 2660, 2853, 2874, 3069, 3150, 3369, 3399, 3438, 3467, 3483, 3484, 3597, 3624, 3870, 3912, 3949, 4091, 4148, 4201, 4202, 4250, 4488, 4508, 4524, 4559, 4563, 4731, 4739, 4781, 4785, 4806, 4809, 4819, 4894, 4915, 4927, 4939, 5014, 5025, 5031, 5151, 5237, 5537, 5547, 5550, 5576, 5617, 5643, 5875, 5919, 5953, 6041, 6042, 6044, 6110, 6198, 6201, 6587, 6594, 6693, 6744, 6753, 6821, 6834, 6854, 6857, 6885, 6924, 6996, 7040, 7171
--------------------------------------------------
Original Row Number: 1
Number of Identical Duplicates: 35
Identical Duplicate Row Numbers: 226, 427, 814, 878, 1070, 1438, 1694, 1778, 1793, 1906, 2040, 2061, 2421, 2556, 2651, 2659, 2753, 3098, 3273, 3295, 3379, 3855, 4128, 4166, 4411, 4531, 4539, 4599, 5733, 6413, 6430, 6616, 6776, 7022, 7108
--------------------------------------------------
Original Row Number: 3
Number of Identical Duplicates: 128
Identical Duplicate Row Numbers: 33, 52, 215, 231, 244, 283, 329, 334, 335, 346, 444, 596, 621, 648, 692, 721, 850, 883, 935, 1025, 1137, 1281, 1283, 1390, 1484, 1553, 1619, 1627, 1670, 1705, 1905, 1972, 1997, 2055, 2116, 2155, 2208, 2412, 2540, 2605, 2636, 2667, 2732, 2742, 2757, 2785, 2870, 2916, 2923, 2996, 3041, 3067, 3104, 3108, 3182, 3193, 3238, 3249, 3270, 3289, 3352, 3439, 3462, 3474, 3475, 3478, 3505, 3510, 3587, 3640, 3655, 3694, 3737, 3738, 3748, 3791, 3883, 3898, 3914, 3963, 3995, 4095, 4106, 4139, 4168, 4261, 4306, 4340, 4428, 4445, 4516, 4584, 4702, 4718, 4791, 4917, 4926, 4984, 5004, 5012, 5119, 5271, 5303, 5357, 5507, 5516, 5521, 5629, 5759, 5816, 5837, 5855, 5867, 5950, 5989, 6035, 6039, 6125, 6153, 6329, 6335, 6340, 6487, 6735, 7054, 7103, 7105, 7137
--------------------------------------------------
Original Row Number: 4
Number of Identical Duplicates: 12
Identical Duplicate Row Numbers: 598, 627, 2778, 2904, 2934, 2944, 3739, 3775, 4957, 5312, 6157, 6829
--------------------------------------------------
Original Row Number: 5
Number of Identical Duplicates: 13
Identical Duplicate Row Numbers: 959, 2218, 3272, 3554, 3670, 3800, 4811, 4905, 4967, 5003, 5469, 6674, 7020
--------------------------------------------------
Original Row Number: 6
Number of Identical Duplicates: 141
Identical Duplicate Row Numbers: 16, 55, 79, 145, 187, 271, 429, 442, 500, 517, 578, 625, 686, 704, 730, 856, 901, 1032, 1056, 1142, 1330, 1422, 1454, 1534, 1540, 1708, 1810, 1819, 1836, 1839, 1883, 1892, 1901, 1954, 1974, 2053, 2167, 2275, 2390, 2449, 2489, 2536, 2621, 2673, 2687, 2699, 2710, 2754, 2763, 2779, 2866, 2876, 3077, 3154, 3168, 3210, 3227, 3268, 3271, 3292, 3301, 3342, 3413, 3452, 3512, 3534, 3536, 3596, 3617, 3629, 3658, 3703, 3740, 3826, 3838, 3891, 3922, 3968, 3999, 4008, 4032, 4084, 4087, 4094, 4101, 4120, 4170, 4195, 4204, 4239, 4276, 4277, 4362, 4385, 4484, 4501, 4551, 4570, 4573, 4814, 4844, 4851, 4863, 4867, 4882, 4888, 5035, 5079, 5089, 5104, 5300, 5389, 5417, 5419, 5470, 5532, 5659, 5781, 5860, 5883, 5891, 5912, 5921, 5944, 6026, 6254, 6287, 6301, 6334, 6346, 6460, 6529, 6556, 6591, 6734, 6783, 6796, 6801, 6993, 7081, 7106
--------------------------------------------------
Original Row Number: 7
Number of Identical Duplicates: 37
Identical Duplicate Row Numbers: 82, 190, 246, 461, 467, 716, 804, 843, 892, 990, 1361, 1520, 1689, 2236, 2296, 2748, 2917, 2929, 2957, 3244, 3706, 3984, 3992, 4033, 4085, 4453, 4572, 4978, 5116, 5375, 5568, 5836, 5907, 6043, 6073, 6123, 6620
--------------------------------------------------
Original Row Number: 8
Number of Identical Duplicates: 1
Identical Duplicate Row Numbers: 6765
--------------------------------------------------
Original Row Number: 9
Number of Identical Duplicates: 18
Identical Duplicate Row Numbers: 579, 911, 1726, 1964, 2058, 2126, 2223, 2300, 2495, 2641, 2676, 2972, 3476, 3957, 4174, 4864, 5130, 6162
--------------------------------------------------
Original Row Number: 11
Number of Identical Duplicates: 137
Identical Duplicate Row Numbers: 18, 76, 91, 131, 238, 281, 300, 319, 383, 423, 472, 473, 503, 652, 655, 748, 909, 1062, 1093, 1158, 1244, 1313, 1336, 1421, 1443, 1473, 1568, 1682, 1720, 1722, 1739, 1765, 1779, 1789, 1827, 1849, 1876, 1921, 2003, 2006, 2033, 2036, 2097, 2102, 2103, 2172, 2231, 2309, 2335, 2379, 2389, 2395, 2396, 2539, 2554, 2555, 2597, 2629, 2795, 2797, 2837, 2898, 2907, 2910, 2980, 3016, 3019, 3038, 3053, 3087, 3090, 3100, 3199, 3297, 3306, 3318, 3358, 3386, 3421, 3465, 3513, 3523, 3527, 3578, 3638, 3718, 3728, 3924, 3945, 3994, 4048, 4115, 4130, 4222, 4240, 4324, 4408, 4413, 4463, 4511, 4537, 4640, 4644, 4812, 4826, 4880, 4886, 4898, 4900, 4904, 4985, 4993, 5179, 5180, 5232, 5366, 5483, 5539, 5564, 5587, 5775, 5893, 5969, 6003, 6251, 6354, 6464, 6474, 6525, 6643, 6656, 6712, 6725, 6812, 6935, 6994, 7138
--------------------------------------------------
Original Row Number: 12
Number of Identical Duplicates: 8
Identical Duplicate Row Numbers: 973, 1269, 2772, 4520, 5198, 5279, 6388, 6395
--------------------------------------------------
Original Row Number: 13
Number of Identical Duplicates: 15
Identical Duplicate Row Numbers: 631, 1190, 1282, 1665, 1856, 1857, 1891, 2927, 4211, 5146, 5796, 5962, 6270, 7045, 7102
--------------------------------------------------
Original Row Number: 14
Number of Identical Duplicates: 14
Identical Duplicate Row Numbers: 358, 456, 1046, 1828, 2157, 3044, 3836, 3993, 4086, 4138, 4345, 4554, 6032, 6886
--------------------------------------------------
Original Row Number: 15
Number of Identical Duplicates: 7
Identical Duplicate Row Numbers: 60, 803, 2095, 4226, 4803, 6360, 6701
--------------------------------------------------
Original Row Number: 16
Number of Identical Duplicates: 141
Identical Duplicate Row Numbers: 6, 55, 79, 145, 187, 271, 429, 442, 500, 517, 578, 625, 686, 704, 730, 856, 901, 1032, 1056, 1142, 1330, 1422, 1454, 1534, 1540, 1708, 1810, 1819, 1836, 1839, 1883, 1892, 1901, 1954, 1974, 2053, 2167, 2275, 2390, 2449, 2489, 2536, 2621, 2673, 2687, 2699, 2710, 2754, 2763, 2779, 2866, 2876, 3077, 3154, 3168, 3210, 3227, 3268, 3271, 3292, 3301, 3342, 3413, 3452, 3512, 3534, 3536, 3596, 3617, 3629, 3658, 3703, 3740, 3826, 3838, 3891, 3922, 3968, 3999, 4008, 4032, 4084, 4087, 4094, 4101, 4120, 4170, 4195, 4204, 4239, 4276, 4277, 4362, 4385, 4484, 4501, 4551, 4570, 4573, 4814, 4844, 4851, 4863, 4867, 4882, 4888, 5035, 5079, 5089, 5104, 5300, 5389, 5417, 5419, 5470, 5532, 5659, 5781, 5860, 5883, 5891, 5912, 5921, 5944, 6026, 6254, 6287, 6301, 6334, 6346, 6460, 6529, 6556, 6591, 6734, 6783, 6796, 6801, 6993, 7081, 7106
--------------------------------------------------
Original Row Number: 17
Number of Identical Duplicates: 36
Identical Duplicate Row Numbers: 912, 1008, 1253, 1351, 1425, 1558, 1585, 1614, 1699, 1870, 1889, 1948, 2171, 2615, 2847, 2942, 2971, 3918, 3947, 3964, 4403, 4638, 4655, 4724, 4860, 4940, 4948, 5038, 5110, 5288, 5405, 5613, 6315, 6810, 7048, 7157
--------------------------------------------------
Original Row Number: 18
Number of Identical Duplicates: 137
Identical Duplicate Row Numbers: 11, 76, 91, 131, 238, 281, 300, 319, 383, 423, 472, 473, 503, 652, 655, 748, 909, 1062, 1093, 1158, 1244, 1313, 1336, 1421, 1443, 1473, 1568, 1682, 1720, 1722, 1739, 1765, 1779, 1789, 1827, 1849, 1876, 1921, 2003, 2006, 2033, 2036, 2097, 2102, 2103, 2172, 2231, 2309, 2335, 2379, 2389, 2395, 2396, 2539, 2554, 2555, 2597, 2629, 2795, 2797, 2837, 2898, 2907, 2910, 2980, 3016, 3019, 3038, 3053, 3087, 3090, 3100, 3199, 3297, 3306, 3318, 3358, 3386, 3421, 3465, 3513, 3523, 3527, 3578, 3638, 3718, 3728, 3924, 3945, 3994, 4048, 4115, 4130, 4222, 4240, 4324, 4408, 4413, 4463, 4511, 4537, 4640, 4644, 4812, 4826, 4880, 4886, 4898, 4900, 4904, 4985, 4993, 5179, 5180, 5232, 5366, 5483, 5539, 5564, 5587, 5775, 5893, 5969, 6003, 6251, 6354, 6464, 6474, 6525, 6643, 6656, 6712, 6725, 6812, 6935, 6994, 7138
--------------------------------------------------
Original Row Number: 19
Number of Identical Duplicates: 39
Identical Duplicate Row Numbers: 124, 152, 515, 785, 1488, 1513, 1523, 1679, 1823, 2024, 2160, 2423, 2608, 2807, 3133, 3340, 3446, 3547, 3787, 3865, 3908, 4056, 4256, 4598, 4604, 5085, 5266, 5315, 5407, 5534, 5697, 5741, 5810, 6106, 6517, 6584, 6853, 6989, 7089
--------------------------------------------------
Original Row Number: 20
Number of Identical Duplicates: 114
Identical Duplicate Row Numbers: 92, 95, 128, 222, 237, 299, 306, 344, 350, 420, 447, 522, 555, 559, 580, 779, 824, 831, 846, 876, 956, 995, 1007, 1114, 1177, 1227, 1262, 1284, 1294, 1328, 1353, 1355, 1363, 1386, 1403, 1452, 1589, 1669, 1685, 1693, 1767, 1786, 2000, 2104, 2127, 2364, 2459, 2552, 2568, 2609, 2644, 2649, 2680, 2811, 2857, 2946, 2951, 2973, 3001, 3116, 3136, 3214, 3223, 3258, 3385, 3422, 3426, 3477, 3506, 3539, 3575, 3633, 3660, 3763, 3861, 4055, 4143, 4165, 4387, 4436, 4493, 4555, 4613, 4689, 4749, 4838, 4852, 4933, 4987, 5175, 5236, 5355, 5362, 5403, 5523, 5623, 5822, 5905, 5906, 6180, 6192, 6219, 6318, 6420, 6445, 6619, 6647, 6705, 6706, 6898, 6973, 7000, 7094, 7149
--------------------------------------------------
Original Row Number: 21
Number of Identical Duplicates: 120
Identical Duplicate Row Numbers: 48, 75, 161, 206, 233, 293, 365, 431, 469, 488, 603, 605, 659, 677, 857, 867, 914, 954, 1098, 1144, 1154, 1178, 1180, 1235, 1266, 1446, 1541, 1559, 1634, 1844, 1874, 1978, 2107, 2156, 2220, 2348, 2378, 2442, 2542, 2592, 2627, 2805, 2868, 2936, 3007, 3029, 3073, 3112, 3153, 3163, 3277, 3329, 3343, 3463, 3485, 3569, 3577, 3666, 3834, 3952, 4058, 4078, 4124, 4131, 4217, 4244, 4389, 4504, 4517, 4529, 4566, 4577, 4652, 4686, 4777, 4965, 4972, 4994, 5076, 5219, 5249, 5255, 5269, 5319, 5329, 5374, 5411, 5414, 5486, 5559, 5598, 5630, 5634, 5650, 5671, 5700, 5710, 5888, 5994, 6046, 6097, 6160, 6212, 6339, 6390, 6514, 6523, 6557, 6720, 6790, 6860, 6882, 6972, 6995, 7034, 7050, 7162, 7165, 7173, 7187
--------------------------------------------------
Original Row Number: 22
Number of Identical Duplicates: 10
Identical Duplicate Row Numbers: 458, 1350, 2930, 3741, 5126, 5447, 6006, 6302, 6548, 6927
--------------------------------------------------
Original Row Number: 23
Number of Identical Duplicates: 1
Identical Duplicate Row Numbers: 3285
--------------------------------------------------
Original Row Number: 24
Number of Identical Duplicates: 11
Identical Duplicate Row Numbers: 410, 411, 1179, 1470, 1587, 3207, 5294, 5412, 5792, 5933, 6461
--------------------------------------------------
Original Row Number: 26
Number of Identical Duplicates: 17
Identical Duplicate Row Numbers: 936, 2013, 2813, 2885, 3155, 3902, 4063, 4096, 4184, 4265, 4646, 5297, 5307, 5890, 6025, 6697, 7160
--------------------------------------------------
Original Row Number: 28
Number of Identical Duplicates: 168
Identical Duplicate Row Numbers: 74, 84, 94, 143, 169, 170, 239, 307, 521, 525, 531, 534, 545, 611, 675, 687, 713, 821, 881, 916, 946, 1018, 1022, 1031, 1036, 1061, 1097, 1111, 1112, 1184, 1203, 1268, 1300, 1335, 1379, 1392, 1590, 1657, 1713, 1833, 1904, 1917, 1938, 1944, 1951, 1958, 2049, 2050, 2091, 2145, 2159, 2177, 2183, 2268, 2306, 2318, 2358, 2384, 2432, 2433, 2476, 2579, 2650, 2664, 2697, 2723, 2737, 2781, 2865, 2909, 3012, 3026, 3094, 3138, 3189, 3194, 3198, 3251, 3308, 3490, 3493, 3514, 3517, 3555, 3580, 3639, 3650, 3659, 3661, 3722, 3724, 3837, 3901, 3975, 4077, 4081, 4103, 4186, 4236, 4251, 4271, 4285, 4337, 4394, 4402, 4476, 4549, 4586, 4593, 4595, 4658, 4666, 4694, 4695, 4716, 4772, 4789, 4805, 4815, 4862, 5019, 5120, 5242, 5326, 5410, 5425, 5443, 5466, 5540, 5574, 5591, 5605, 5646, 5868, 5927, 5934, 5956, 5971, 5992, 6009, 6030, 6086, 6130, 6131, 6134, 6174, 6283, 6303, 6311, 6405, 6456, 6479, 6480, 6567, 6601, 6606, 6613, 6655, 6756, 6757, 6851, 6855, 6878, 6906, 6956, 7029, 7035, 7184
--------------------------------------------------
Original Row Number: 29
Number of Identical Duplicates: 15
Identical Duplicate Row Numbers: 570, 1071, 1728, 2088, 2548, 2714, 2859, 3141, 3595, 3646, 3707, 3788, 6482, 6586, 6748
--------------------------------------------------
Original Row Number: 30
Number of Identical Duplicates: 42
Identical Duplicate Row Numbers: 85, 324, 637, 1165, 1437, 1677, 1756, 1835, 1915, 1920, 2142, 2272, 2611, 3203, 3553, 3856, 3931, 4051, 4219, 4231, 4356, 4414, 4446, 4459, 4590, 4730, 4733, 4876, 4909, 4919, 4959, 5040, 5274, 5495, 5585, 6118, 6264, 6268, 6444, 6858, 6941, 7110
--------------------------------------------------
Original Row Number: 32
Number of Identical Duplicates: 7
Identical Duplicate Row Numbers: 116, 2114, 2182, 2457, 2801, 4480, 6314
--------------------------------------------------
Original Row Number: 33
Number of Identical Duplicates: 128
Identical Duplicate Row Numbers: 3, 52, 215, 231, 244, 283, 329, 334, 335, 346, 444, 596, 621, 648, 692, 721, 850, 883, 935, 1025, 1137, 1281, 1283, 1390, 1484, 1553, 1619, 1627, 1670, 1705, 1905, 1972, 1997, 2055, 2116, 2155, 2208, 2412, 2540, 2605, 2636, 2667, 2732, 2742, 2757, 2785, 2870, 2916, 2923, 2996, 3041, 3067, 3104, 3108, 3182, 3193, 3238, 3249, 3270, 3289, 3352, 3439, 3462, 3474, 3475, 3478, 3505, 3510, 3587, 3640, 3655, 3694, 3737, 3738, 3748, 3791, 3883, 3898, 3914, 3963, 3995, 4095, 4106, 4139, 4168, 4261, 4306, 4340, 4428, 4445, 4516, 4584, 4702, 4718, 4791, 4917, 4926, 4984, 5004, 5012, 5119, 5271, 5303, 5357, 5507, 5516, 5521, 5629, 5759, 5816, 5837, 5855, 5867, 5950, 5989, 6035, 6039, 6125, 6153, 6329, 6335, 6340, 6487, 6735, 7054, 7103, 7105, 7137
--------------------------------------------------
Original Row Number: 34
Number of Identical Duplicates: 15
Identical Duplicate Row Numbers: 389, 404, 529, 1497, 1556, 2836, 3025, 3643, 4293, 4530, 4914, 5020, 5356, 5506, 6513
--------------------------------------------------
Original Row Number: 35
Number of Identical Duplicates: 36
Identical Duplicate Row Numbers: 165, 189, 516, 864, 904, 1100, 1418, 1419, 1762, 1768, 1896, 2506, 2567, 2633, 2762, 2998, 3372, 3375, 4199, 4499, 4890, 5001, 5032, 5211, 5224, 5229, 5536, 5592, 5695, 6083, 6253, 6293, 6455, 6528, 6572, 7107
--------------------------------------------------
Original Row Number: 36
Number of Identical Duplicates: 9
Identical Duplicate Row Numbers: 39, 756, 941, 2206, 6116, 6739, 6759, 6978, 7148
--------------------------------------------------
Original Row Number: 37
Number of Identical Duplicates: 19
Identical Duplicate Row Numbers: 140, 338, 448, 601, 649, 807, 861, 1333, 1582, 1936, 1995, 3013, 3550, 4065, 4161, 4527, 5484, 5873, 6305
--------------------------------------------------
Original Row Number: 39
Number of Identical Duplicates: 9
Identical Duplicate Row Numbers: 36, 756, 941, 2206, 6116, 6739, 6759, 6978, 7148
--------------------------------------------------
Original Row Number: 43
Number of Identical Duplicates: 17
Identical Duplicate Row Numbers: 180, 554, 684, 694, 1326, 1462, 2525, 2997, 3702, 4070, 4177, 4422, 4780, 6880, 6959, 6965, 7112
--------------------------------------------------
Original Row Number: 44
Number of Identical Duplicates: 15
Identical Duplicate Row Numbers: 502, 697, 714, 791, 1812, 1897, 2118, 2373, 2404, 2751, 3147, 4007, 5575, 6933, 7194
--------------------------------------------------
Original Row Number: 45
Number of Identical Duplicates: 11
Identical Duplicate Row Numbers: 68, 1053, 1649, 1752, 1922, 2062, 2288, 2630, 2663, 4855, 5562
--------------------------------------------------
Original Row Number: 47
Number of Identical Duplicates: 18
Identical Duplicate Row Numbers: 535, 1110, 1651, 1769, 2196, 2333, 2962, 3167, 3400, 3600, 3863, 3913, 4653, 4706, 5138, 5248, 5589, 7076
--------------------------------------------------
Original Row Number: 48
Number of Identical Duplicates: 120
Identical Duplicate Row Numbers: 21, 75, 161, 206, 233, 293, 365, 431, 469, 488, 603, 605, 659, 677, 857, 867, 914, 954, 1098, 1144, 1154, 1178, 1180, 1235, 1266, 1446, 1541, 1559, 1634, 1844, 1874, 1978, 2107, 2156, 2220, 2348, 2378, 2442, 2542, 2592, 2627, 2805, 2868, 2936, 3007, 3029, 3073, 3112, 3153, 3163, 3277, 3329, 3343, 3463, 3485, 3569, 3577, 3666, 3834, 3952, 4058, 4078, 4124, 4131, 4217, 4244, 4389, 4504, 4517, 4529, 4566, 4577, 4652, 4686, 4777, 4965, 4972, 4994, 5076, 5219, 5249, 5255, 5269, 5319, 5329, 5374, 5411, 5414, 5486, 5559, 5598, 5630, 5634, 5650, 5671, 5700, 5710, 5888, 5994, 6046, 6097, 6160, 6212, 6339, 6390, 6514, 6523, 6557, 6720, 6790, 6860, 6882, 6972, 6995, 7034, 7050, 7162, 7165, 7173, 7187
--------------------------------------------------
Original Row Number: 50
Number of Identical Duplicates: 27
Identical Duplicate Row Numbers: 72, 353, 494, 1209, 1226, 1444, 1467, 1898, 2026, 3000, 3032, 3531, 4321, 4482, 4589, 5036, 5256, 5258, 5264, 5821, 6050, 6067, 6079, 6342, 6917, 6964, 7072
--------------------------------------------------
Original Row Number: 51
Number of Identical Duplicates: 126
Identical Duplicate Row Numbers: 0, 98, 147, 175, 227, 253, 276, 369, 372, 376, 392, 426, 495, 532, 591, 604, 696, 782, 825, 833, 844, 860, 939, 943, 945, 978, 998, 1040, 1051, 1054, 1083, 1095, 1156, 1171, 1182, 1186, 1214, 1228, 1303, 1530, 1571, 1592, 1630, 1676, 1759, 1824, 1851, 1939, 2178, 2188, 2210, 2241, 2253, 2547, 2604, 2660, 2853, 2874, 3069, 3150, 3369, 3399, 3438, 3467, 3483, 3484, 3597, 3624, 3870, 3912, 3949, 4091, 4148, 4201, 4202, 4250, 4488, 4508, 4524, 4559, 4563, 4731, 4739, 4781, 4785, 4806, 4809, 4819, 4894, 4915, 4927, 4939, 5014, 5025, 5031, 5151, 5237, 5537, 5547, 5550, 5576, 5617, 5643, 5875, 5919, 5953, 6041, 6042, 6044, 6110, 6198, 6201, 6587, 6594, 6693, 6744, 6753, 6821, 6834, 6854, 6857, 6885, 6924, 6996, 7040, 7171
--------------------------------------------------
Original Row Number: 52
Number of Identical Duplicates: 128
Identical Duplicate Row Numbers: 3, 33, 215, 231, 244, 283, 329, 334, 335, 346, 444, 596, 621, 648, 692, 721, 850, 883, 935, 1025, 1137, 1281, 1283, 1390, 1484, 1553, 1619, 1627, 1670, 1705, 1905, 1972, 1997, 2055, 2116, 2155, 2208, 2412, 2540, 2605, 2636, 2667, 2732, 2742, 2757, 2785, 2870, 2916, 2923, 2996, 3041, 3067, 3104, 3108, 3182, 3193, 3238, 3249, 3270, 3289, 3352, 3439, 3462, 3474, 3475, 3478, 3505, 3510, 3587, 3640, 3655, 3694, 3737, 3738, 3748, 3791, 3883, 3898, 3914, 3963, 3995, 4095, 4106, 4139, 4168, 4261, 4306, 4340, 4428, 4445, 4516, 4584, 4702, 4718, 4791, 4917, 4926, 4984, 5004, 5012, 5119, 5271, 5303, 5357, 5507, 5516, 5521, 5629, 5759, 5816, 5837, 5855, 5867, 5950, 5989, 6035, 6039, 6125, 6153, 6329, 6335, 6340, 6487, 6735, 7054, 7103, 7105, 7137
--------------------------------------------------
Original Row Number: 53
Number of Identical Duplicates: 18
Identical Duplicate Row Numbers: 678, 1126, 1274, 1433, 1486, 2246, 2305, 3109, 3130, 3204, 3217, 3729, 4931, 4956, 5226, 6091, 6164, 6412
--------------------------------------------------
Original Row Number: 54
Number of Identical Duplicates: 21
Identical Duplicate Row Numbers: 479, 626, 643, 749, 808, 1477, 1940, 2121, 2194, 3201, 3867, 4026, 4450, 4708, 5070, 5153, 5503, 5973, 5987, 6080, 6421
--------------------------------------------------
Original Row Number: 55
Number of Identical Duplicates: 141